### PR TITLE
Fix rule handler

### PR DESCRIPTION
**Pull request by otacke**

### CODE REVIEW

**Comment by otacke** [comment]
@rezeau Sorry, I had created that pull request on your master branch, not on your working branch, so the original pull request is not yet updated. This should take care of it. Sorry again!

**Comment by rezeau** [comment]
Ah, OK, I just realized that! Your fix is of course much more elegant. I've tested it and it's OK.
What should I do now so that my pull request #6 on the H5 github is updated?

**Comment by otacke** [comment]
@rezeau It has been updated automatically already.

**Comment by rezeau** [comment]
@otacke I didn't know that or maybe I did when I was more active on my github but had forgotten. Thanks again for a nice fix.

**Pull request merged**
